### ISSUE TITLE
週六表示邊緣

### ISSUE THREAD

**Issue by YuerLee** [x3388638/KeBiau#1]
<img width="457" alt="2017-09-10 11 54 27" src="https://user-images.githubusercontent.com/2075566/30246015-71cbfcc2-961f-11e7-926f-2efe17fb50c8.png">

**Comment by x3388638** [comment]
@passerbyid 
不要急嘛
邊緣的東西當然最後處理

**Comment by x3388638** [comment]
https://github.com/x3388638/KeBiau/commit/590d690dfebdccee1478fbfec26eabe4efe61253
