### ISSUE TITLE
進階過濾功能

### ISSUE THREAD

**Issue by JackKuo-tw** [x3388638/KeBiau#2]
大大能不能弄個教師、教室、時段過濾的功能呀～
登入教務系統好麻煩
我也希望我會 ReactJS 就能發 PR 給你了

**Comment by x3388638** [comment]
@JackKuo-tw 感謝提供意見，會再參考參考~

**Comment by x3388638** [comment]
https://github.com/x3388638/KeBiau/commit/20d7a4b6b0c87aed43cfd9d0286a59c8eb4a9c18
https://github.com/x3388638/KeBiau/commit/65b006b804c2289e22075d2703afe6aaec189ab6
https://github.com/x3388638/KeBiau/commit/b1d8a8b498040221d32b730042f15374fd43f4ea
