### ISSUE TITLE
課綱鏈接

### ISSUE THREAD

**Issue by themikesam** [x3388638/KeBiau#4]
打開後，顯示
404 - 找不到檔案或目錄。

或許不是開發者的問題~ 純屬回報錯誤

**Comment by x3388638** [comment]
@themikesam 
網頁版教務系統改版，原課綱頁面被移除
有空再修改
感謝回報～

**Comment by x3388638** [comment]
fixed https://github.com/x3388638/KeBiau/commit/397914dbb1fa8d665751db74475a0d90d306115b
